spring.application.name=notification-service
server.port=8084

# SMTP Server
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=587

spring.mail.username=a9d6787027eaa8
spring.mail.password=74884f895353ad

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.debug=true

# RabbitMQ
spring.rabbitmq.host=localhost
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest

# Gmail
gmail.credentials-path=credentials.json
gmail.tokens-directory=notification-service/tokens
